/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jl.historiapp.vista;

import com.jl.historia.entidad.Evolucion;
import com.jl.historia.entidad.Historia;
import com.jl.historia.entidad.Paciente;
import com.jl.historia.entidad.Receta;
import com.jl.historiapp.controlador.EvolucionControlador;
import com.jl.historiapp.controlador.HistoriaControlador;
import com.jl.historiapp.controlador.PacienteControlador;
import com.jl.historiapp.controlador.RecetaControlador;
import com.jl.historiapp.servicio.ConexionServicio;
import com.jl.historiapp.utilitarios.ExcepcionGeneral;
import com.toedter.calendar.JDateChooser;
import java.awt.event.KeyEvent;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author famleto
 */
public class CRUDHistoria extends javax.swing.JFrame {

    /**
     * Creates new form GuardaPaciente
     */
    public int transaccion;
    //hola mundo!!!!
    private PacienteControlador pacienteControlador = new PacienteControlador();
    private HistoriaControlador historiaControlador = new HistoriaControlador();
    private RecetaControlador recetaControlador = new RecetaControlador();
    private EvolucionControlador evolucionControlador = new EvolucionControlador();
    public int idPaciente;
    private Evolucion evolucion;
    private Evolucion evolution;
    public Receta receta;
    public Historia historia;
    private Paciente paciente;
    private int transaccionEvolucion = 1;
    private int transaccionReceta = 1;

    public CRUDHistoria() {
        initComponents();

        setResizable(false);
        setLocationRelativeTo(null);
        btnAgregarEvolucion.setEnabled(false);
        btnVerReceta.setEnabled(false);
        btnGuardar.setEnabled(false);
        cmbSexo.setEnabled(false);
        cmbEstadoCivil.setEnabled(false);
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");

        txtFecha.setText(formato.format(new Date()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        txtEdad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbSexo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        cmbEstadoCivil = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaMotivo = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaEnfermedad = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnVerReceta = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnAgregarEvolucion = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        txaDiagnostico = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        btnVerEvolucion = new javax.swing.JButton();
        btnAgregarRecetas = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        txaEvolucion = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txaReceta = new javax.swing.JTextArea();
        btnImprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("Fecha:");

        txtFecha.setText("jLabel5");

        jLabel6.setText("N°");

        txtCodigo.setEditable(false);
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(txtFecha)
                .addGap(92, 92, 92)
                .addComponent(jLabel6)
                .addGap(30, 30, 30)
                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFecha)
                    .addComponent(jLabel6)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        txtEdad.setEditable(false);
        txtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadActionPerformed(evt);
            }
        });
        txtEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEdadKeyTyped(evt);
            }
        });

        jLabel1.setText("Nombre:");

        jLabel2.setText("Edad:");

        txtNombre.setEditable(false);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        jLabel3.setText("Sexo:");

        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino", " " }));

        jLabel11.setText("Estado Civil:");

        jLabel12.setText("DNI:");

        txtDNI.setEditable(false);
        txtDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDNIActionPerformed(evt);
            }
        });
        txtDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDNIKeyTyped(evt);
            }
        });

        cmbEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soltero", "Conviviente", "Casado", "Viudo", "Divorciado", " " }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(6, 6, 6)
                        .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1)
                        .addGap(12, 12, 12)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(28, 28, 28)
                        .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel11)
                        .addGap(12, 12, 12)
                        .addComponent(cmbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel11)))
                    .addComponent(cmbSexo))
                .addContainerGap())
        );

        txaMotivo.setEditable(false);
        txaMotivo.setColumns(20);
        txaMotivo.setRows(5);
        jScrollPane1.setViewportView(txaMotivo);

        jLabel7.setText("Motivo de la Consulta");

        jLabel8.setText("Enfermedad Actual");

        txaEnfermedad.setEditable(false);
        txaEnfermedad.setColumns(20);
        txaEnfermedad.setRows(5);
        jScrollPane2.setViewportView(txaEnfermedad);

        jLabel9.setText("Evolución");

        jLabel10.setText("R.P.");

        btnVerReceta.setText("Ver Recetas");
        btnVerReceta.setEnabled(false);
        btnVerReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerRecetaActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar Historia");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnAgregarEvolucion.setText("Agregar");
        btnAgregarEvolucion.setEnabled(false);
        btnAgregarEvolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEvolucionActionPerformed(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buscar.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eliminar.png"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/actualizar.png"))); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/agregar.png"))); // NOI18N
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        txaDiagnostico.setEditable(false);
        txaDiagnostico.setColumns(20);
        txaDiagnostico.setRows(5);
        jScrollPane5.setViewportView(txaDiagnostico);

        jLabel13.setText("Diagnóstico");

        btnVerEvolucion.setText("Ver Evolución");
        btnVerEvolucion.setEnabled(false);
        btnVerEvolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerEvolucionActionPerformed(evt);
            }
        });

        btnAgregarRecetas.setText("Agregar");
        btnAgregarRecetas.setEnabled(false);
        btnAgregarRecetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarRecetasActionPerformed(evt);
            }
        });

        txaEvolucion.setEditable(false);
        txaEvolucion.setColumns(20);
        txaEvolucion.setRows(5);
        jScrollPane6.setViewportView(txaEvolucion);

        txaReceta.setColumns(20);
        txaReceta.setRows(5);
        jScrollPane4.setViewportView(txaReceta);

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3-Gray-Printer-icon.png"))); // NOI18N
        btnImprimir.setEnabled(false);
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 26, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnAgregarEvolucion)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnVerEvolucion)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(400, 400, 400)
                                .addComponent(btnAgregarRecetas)
                                .addGap(18, 18, 18)
                                .addComponent(btnVerReceta))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(btnGuardar)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(btnAgregarEvolucion)
                    .addComponent(btnVerEvolucion))
                .addGap(2, 2, 2)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnVerReceta)
                        .addComponent(btnAgregarRecetas)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        if (txtDNI.getText().equals("") || txtNombre.getText().equals("") || txtEdad.getText().equals("") || txaMotivo.getText().equals("") || txaEnfermedad.getText().equals("") || txaDiagnostico.getText().equals("") || txaEvolucion.getText().equals("") || txaReceta.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Todos los campos en este formulario deben ser llenados");
        } else {
            if (txtDNI.getText().length() < 9) {
                if (Integer.parseInt(txtEdad.getText()) <= 150) {
                    if (transaccion == 1) {
                        Paciente paciente = new Paciente();
                        paciente.setDni(txtDNI.getText());
                        paciente.setNombre(txtNombre.getText());
                        paciente.setEdad(Integer.parseInt(txtEdad.getText()));
                        paciente.setSexo(cmbSexo.getSelectedItem().toString());
                        paciente.setEstaoCivil(cmbEstadoCivil.getSelectedItem().toString());
                        paciente = pacienteControlador.guardarPaciente(paciente);

                        Historia historia = new Historia();
                        historia.setPacienteId(paciente);
                        historia.setMotivo(txaMotivo.getText());
                        historia.setEnfermedadActual(txaEnfermedad.getText());
                        historia.setDiagnostico(txaDiagnostico.getText());

                        historia = historiaControlador.guardarHistoria(historia);

                        evolucion = new Evolucion();
                        evolucion.setDescripcion(txaReceta.getText());
                        evolucion.setHistoriaId(historia);
                        evolucionControlador.guardarEvolucion(evolucion);

                        receta = new Receta();
                        receta.setFecha(new Date());
                        receta.setMedicinas(txaReceta.getText());
                        receta.setHistorias(historia);
                        recetaControlador.guaradarReceta(receta);
                        txtCodigo.setText(historia.getCodigoHistoria());

                    } else {
                        paciente.setDni(txtDNI.getText());
                        paciente.setNombre(txtNombre.getText());
                        paciente.setEdad(Integer.parseInt(txtEdad.getText()));
                        paciente.setSexo(cmbSexo.getSelectedItem().toString());
                        paciente.setEstaoCivil(cmbEstadoCivil.getSelectedItem().toString());
                        paciente = pacienteControlador.guardarPaciente(paciente);

                        historia.setPacienteId(paciente);
                        historia.setMotivo(txaMotivo.getText());
                        historia.setEnfermedadActual(txaEnfermedad.getText());
                        historia.setDiagnostico(txaDiagnostico.getText());

                        historia = historiaControlador.guardarHistoria(historia);
                        if (transaccionEvolucion == 1) {
                            evolucionControlador.guardarEvolucion(evolucion);
                        }
                        if (transaccionReceta == 1) {
                            recetaControlador.guaradarReceta(receta);
                        }
                    }

                    txtDNI.setEditable(true);
                    txtNombre.setEditable(true);
                    txtEdad.setEditable(true);
                    cmbSexo.setEditable(true);
                    cmbEstadoCivil.setEditable(true);
                    txaMotivo.setEditable(true);
                    txaEnfermedad.setEditable(true);
                    txaDiagnostico.setEditable(true);
                    txaEvolucion.setEditable(true);
                    txaReceta.setEditable(true);
                    cmbSexo.setEnabled(true);
                    cmbEstadoCivil.setEnabled(true);
                    btnAgregarEvolucion.setEnabled(true);
                    btnVerEvolucion.setEnabled(true);
                    btnVerReceta.setEnabled(true);
                    btnAgregarRecetas.setEnabled(true);
                } else {
                    JOptionPane.showMessageDialog(null, "La edad no puede ser mayor a 150 años");
                }
            } else {
                JOptionPane.showMessageDialog(null, "El dni no puede ser mayor a 8 dígitos");
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        txtDNI.setEditable(true);
        txtDNI.setText("");
        txtNombre.setEditable(true);
        txtNombre.setText("");
        txtEdad.setEditable(true);
        txtEdad.setText("");
        cmbSexo.setEnabled(true);
        cmbEstadoCivil.setEnabled(true);
        txaMotivo.setEditable(true);
        txaMotivo.setText("");
        txaEnfermedad.setEditable(true);
        txaEnfermedad.setText("");
        txaDiagnostico.setEditable(true);
        txaDiagnostico.setText("");
        txaEvolucion.setText("");
        txaEvolucion.setEditable(true);
        txaReceta.setEditable(true);
        txaReceta.setText("");
        btnGuardar.setEnabled(true);
        btnImprimir.setEnabled(false);
        transaccion = 1;
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void txtDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNIActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        txtDNI.setText("");
        txtNombre.setText("");
        txtEdad.setText("");
        txaEnfermedad.setText("");
        txaMotivo.setText("");
        txaDiagnostico.setText("");
        txaEvolucion.setText("");
        txaReceta.setText("");
        transaccion = 2;
        String[] botones = {"Buscar por Paciente", "Busca por Código de Historia", "Cancelar"};
        int variable = JOptionPane.showOptionDialog(null, "¿Como Desea Buscar la Historia?", "Busqueda de Historias", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE, null, botones, botones[0]);
        if (variable == 0) {
            ListaPacientes listaPacientes = new ListaPacientes(this);
            listaPacientes.setVisible(true);
            btnGuardar.setEnabled(true);
            configurarControles(true);

        } else if (variable == 1) {
            ListarHistorias listarHistorias = new ListarHistorias(this);
            listarHistorias.setVisible(true);
            configurarControles(true);
        } else {
            //
        }
        

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnAgregarEvolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEvolucionActionPerformed
        transaccionEvolucion = 2;
        try {
            if (evolucion.getDescripcion().equals(txaEvolucion.getText())) {
                throw new ExcepcionGeneral("Debe Colocar una descripcion distinta");
            }
            evolucion = new Evolucion();
            evolucion.setHistoriaId(historia);
            evolucion.setDescripcion(txaEvolucion.getText());
            evolucionControlador.guardarEvolucion(evolucion);
        } catch (ExcepcionGeneral ex) {
        }
    }//GEN-LAST:event_btnAgregarEvolucionActionPerformed

    private void btnAgregarRecetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarRecetasActionPerformed
        try {
            transaccionReceta = 2;
            if (receta.getMedicinas().equals(txaReceta.getText())) {
                throw new ExcepcionGeneral("Debe Colocar una descripcion distinta");
            }
            receta = new Receta();
            receta.setHistorias(historia);
            receta.setMedicinas(txaReceta.getText());
            recetaControlador.guaradarReceta(receta);
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_btnAgregarRecetasActionPerformed

    private void btnVerEvolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerEvolucionActionPerformed
        ListaEvoluciones listaEvoluciones = new ListaEvoluciones(this);
        listaEvoluciones.setVisible(true);
    }//GEN-LAST:event_btnVerEvolucionActionPerformed

    private void btnVerRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerRecetaActionPerformed
        ListaRecetas listaRecetas = new ListaRecetas(this);
        listaRecetas.setVisible(true);
    }//GEN-LAST:event_btnVerRecetaActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        new ListarHistorias(this).setVisible(true);
        transaccion = 3;
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        transaccion = 4;
        new ListarHistorias(this).setVisible(true);

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        try {
            
            String rutaReporte= "C:\\receta.jasper";
         
            JDateChooser jd = new JDateChooser();
            String message ="Ingrese la fecha de la próxima consulta:\n";
            Object[] params = {message,jd};
            JOptionPane.showConfirmDialog(null,params,"Fecha de la próxima consulta", JOptionPane.PLAIN_MESSAGE);
            
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            Date fecha= jd.getDate();
            
            Map parametros = new HashMap();
            parametros.put("prox_consulta", fecha);
            parametros.put("receta",receta.getId());
            
            // se muestra en una ventana aparte para su descarga
            JasperPrint jasperPrintWindow = JasperFillManager.fillReport(
                    rutaReporte, parametros,
                    ConexionServicio.conectar());
            JasperViewer jasperViewer = new JasperViewer(jasperPrintWindow,false);
            jasperViewer.setVisible(true);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void txtDNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDNIKeyTyped
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDNIKeyTyped

    private void txtEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadKeyTyped
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtEdadKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        if (!Character.isLetter(evt.getKeyChar()) && !(evt.getKeyChar() == KeyEvent.VK_SPACE) && !(evt.getKeyChar() == KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    public void llenarDatosHistoriaPorPaciente(int idPaciente) {

        paciente = pacienteControlador.mostrarDatosPaciente(idPaciente);
        txtDNI.setText(paciente.getDni());
        txtNombre.setText(paciente.getNombre());
        txtEdad.setText(paciente.getEdad().toString());
        cmbSexo.setSelectedItem(paciente.getSexo());
        cmbEstadoCivil.setSelectedItem(paciente.getEstaoCivil());
        historia = historiaControlador.mostrarDatosHistoriaPorPaciente(paciente);
        txaMotivo.setText(historia.getMotivo());
        txaEnfermedad.setText(historia.getEnfermedadActual());
        txaDiagnostico.setText(historia.getDiagnostico());
        evolucion = evolucionControlador.mostrarUltimaEvolucion(historia);
        txaEvolucion.setText(evolucion.getDescripcion());
        receta = recetaControlador.mostrarUltimaReceta(historia);
        txaReceta.setText(receta.getMedicinas());
        btnImprimir.setEnabled(true);
    }

    public void llenarEvolucion(int idEvolucion) {
        evolution = evolucionControlador.obtenerEvolucionPorId(idEvolucion);
        txaEvolucion.setText(evolution.getDescripcion());
    }

    public void llenarReceta(int idReceta) {
        receta = recetaControlador.mostrarRecetaPorId(idReceta);
        txaReceta.setText("");
        txaReceta.append(receta.getMedicinas());
    }

    public void configurarControles(boolean flag) {
        btnAgregarEvolucion.setEnabled(flag);
        btnAgregarRecetas.setEnabled(flag);
        btnVerEvolucion.setEnabled(flag);
        btnVerReceta.setEnabled(flag);
        txtDNI.setEditable(flag);
        txtNombre.setEditable(flag);
        txtEdad.setEditable(flag);
        txaMotivo.setEditable(flag);
        txaEnfermedad.setEditable(flag);
        txaDiagnostico.setEditable(flag);
        txaEvolucion.setEditable(flag);
        txaReceta.setEditable(flag);
        btnGuardar.setEnabled(flag);
        cmbSexo.setEnabled(flag);
        cmbEstadoCivil.setEnabled(flag);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUDHistoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUDHistoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUDHistoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUDHistoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUDHistoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarEvolucion;
    private javax.swing.JButton btnAgregarRecetas;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnVerEvolucion;
    private javax.swing.JButton btnVerReceta;
    private javax.swing.JComboBox<String> cmbEstadoCivil;
    private javax.swing.JComboBox<String> cmbSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea txaDiagnostico;
    private javax.swing.JTextArea txaEnfermedad;
    private javax.swing.JTextArea txaEvolucion;
    private javax.swing.JTextArea txaMotivo;
    public javax.swing.JTextArea txaReceta;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JLabel txtFecha;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

}
