/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jl.historiapp.vista;

import com.jl.historia.entidad.Evolucion;
import com.jl.historiapp.controlador.EvolucionControlador;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author famleto
 */
public class ListaEvoluciones extends javax.swing.JFrame {

    private CRUDHistoria crudHistoria;
    private EvolucionControlador evolucionControlador = new EvolucionControlador();
    public int idEvolucion;
    private DefaultTableModel modelo;
    public ListaEvoluciones() {
        initComponents();

    }

    public ListaEvoluciones(CRUDHistoria crudHistoria) {
        initComponents();
        this.crudHistoria = crudHistoria;
        modelo = (DefaultTableModel) tblEvoluciones.getModel();
        Object[] rowData = new Object[6];
        List<Evolucion> evoluciones = evolucionControlador.listarEvoluciones(crudHistoria.historia);

        for (int i = 0; i < evoluciones.size(); i++) {
            rowData[0] = evoluciones.get(i).getId();
            rowData[1] = evoluciones.get(i).getDescripcion();
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");            
            rowData[2] = formato.format(evoluciones.get(i).getFecha());

            modelo.addRow(rowData);
        }
        tblEvoluciones.getColumnModel().getColumn(0).setMinWidth(0);
        tblEvoluciones.getColumnModel().getColumn(0).setMaxWidth(0);
        tblEvoluciones.getColumnModel().getColumn(0).setWidth(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEvoluciones = new javax.swing.JTable();
        btnSeleccionar = new javax.swing.JButton();
        dchDesde = new com.toedter.calendar.JDateChooser();
        dchHasta = new com.toedter.calendar.JDateChooser();
        btnLIstar = new javax.swing.JButton();
        txtHasta = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Evoluciones");

        tblEvoluciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Descripcion", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEvoluciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEvolucionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEvoluciones);

        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        dchDesde.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dchDesdePropertyChange(evt);
            }
        });

        dchHasta.setEnabled(false);
        dchHasta.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dchHastaPropertyChange(evt);
            }
        });

        btnLIstar.setText("Listar");
        btnLIstar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLIstarActionPerformed(evt);
            }
        });

        txtHasta.setText("Hasta:");

        jLabel1.setText("Desde:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(btnSeleccionar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(dchDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(txtHasta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dchHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLIstar)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dchDesde, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dchHasta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addComponent(txtHasta)
                    .addComponent(btnLIstar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSeleccionar)
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblEvolucionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEvolucionesMouseClicked
        JTable tabla = (JTable) evt.getSource();
        int fila = tabla.getSelectedRow();
        int columna = 0;
        idEvolucion = Integer.valueOf(tblEvoluciones.getModel().getValueAt(fila, columna).toString());

    }//GEN-LAST:event_tblEvolucionesMouseClicked

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        this.crudHistoria.llenarEvolucion(idEvolucion);
        this.dispose();
        
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void dchHastaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dchHastaPropertyChange
       
        Date fechaDesde = dchDesde.getDate();
        Date fechaHasta = dchHasta.getDate();
        if (dchDesde.getDate() != null && dchHasta.getDate() != null) {
            List<Evolucion> evoluciones = evolucionControlador.buscarRecetaPorFecha(fechaDesde, fechaHasta, this.crudHistoria.historia);
            modelo = (DefaultTableModel) this.tblEvoluciones.getModel();
            modelo.setRowCount(0);
            Object[] filadata = new Object[3];
            for (Evolucion evolucion : evoluciones) {
                filadata[0] = evolucion.getId();
                filadata[1] = evolucion.getDescripcion();
                filadata[2] = evolucion.getFecha();
                modelo.addRow(filadata);
            }
        }
    }//GEN-LAST:event_dchHastaPropertyChange

    private void btnLIstarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLIstarActionPerformed
        modelo.setRowCount(0);
        modelo = (DefaultTableModel) tblEvoluciones.getModel();
        Object[] rowData = new Object[3];
        List<Evolucion> evoluciones = evolucionControlador.listarEvoluciones(this.crudHistoria.historia);

        for (int i = 0; i < evoluciones.size(); i++) {
            rowData[0] = evoluciones.get(i).getId();
            rowData[1] = evoluciones.get(i).getDescripcion();
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");            
            rowData[2] = formato.format(evoluciones.get(i).getFecha());

            modelo.addRow(rowData);
        }
        tblEvoluciones.getColumnModel().getColumn(0).setMinWidth(0);
        tblEvoluciones.getColumnModel().getColumn(0).setMaxWidth(0);
        tblEvoluciones.getColumnModel().getColumn(0).setWidth(0);
    }//GEN-LAST:event_btnLIstarActionPerformed

    private void dchDesdePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dchDesdePropertyChange
        dchHasta.setEnabled(true);
    }//GEN-LAST:event_dchDesdePropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaEvoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaEvoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaEvoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaEvoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaEvoluciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLIstar;
    private javax.swing.JButton btnSeleccionar;
    private com.toedter.calendar.JDateChooser dchDesde;
    private com.toedter.calendar.JDateChooser dchHasta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEvoluciones;
    private javax.swing.JLabel txtHasta;
    // End of variables declaration//GEN-END:variables
}
