/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jl.historiapp.vista;

import com.jl.historia.entidad.Paciente;
import com.jl.historiapp.controlador.PacienteControlador;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author famleto
 */
public class ListaPacientes extends javax.swing.JFrame {

    private PacienteControlador pacienteControlador = new PacienteControlador();
    public int idPaciente;
    CRUDHistoria crudHistoria;
    DefaultTableModel modelo;
    String codigoHistoria;
    public ListaPacientes(CRUDHistoria crudHistoria) {
        this.crudHistoria = crudHistoria;
        initComponents();
        modelo = (DefaultTableModel) tblPacientes.getModel();
        Object[] rowData = new Object[6];
        List<Paciente> pacientes = pacienteControlador.listarPacientes();

        for (int i = 0; i < pacientes.size(); i++) {
            rowData[0] = pacientes.get(i).getDni();
            rowData[1] = pacientes.get(i).getNombre();
            rowData[2] = pacientes.get(i).getEdad();
            rowData[3] = pacientes.get(i).getSexo();
            rowData[4] = pacientes.get(i).getEstaoCivil();
            rowData[5] = pacientes.get(i).getId();
            modelo.addRow(rowData);
        }
        tblPacientes.getColumnModel().getColumn(5).setMinWidth(0);
        tblPacientes.getColumnModel().getColumn(5).setMaxWidth(0);
        tblPacientes.getColumnModel().getColumn(5).setWidth(0);
    }

    public ListaPacientes() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) tblPacientes.getModel();
        Object[] rowData = new Object[6];
        List<Paciente> pacientes = pacienteControlador.listarPacientes();

        for (int i = 0; i < pacientes.size(); i++) {
            rowData[0] = pacientes.get(i).getDni();
            rowData[1] = pacientes.get(i).getNombre();
            rowData[2] = pacientes.get(i).getEdad();
            rowData[3] = pacientes.get(i).getSexo();
            rowData[4] = pacientes.get(i).getEstaoCivil();
            rowData[5] = pacientes.get(i).getId();
            modelo.addRow(rowData);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPacientes = new javax.swing.JTable();
        btnSeleccionar = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tblPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DNI", "Nombres", "Edad", "Sexo", "Estado Civil", "Id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPacientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPacientes);

        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoKeyPressed(evt);
            }
        });

        txtNombre.setText("Nombres:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(211, 211, 211)
                                .addComponent(btnSeleccionar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(txtNombre)
                                .addGap(35, 35, 35)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSeleccionar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPacientesMouseClicked
        JTable tabla = (JTable) evt.getSource();
        int fila = tabla.getSelectedRow();
        int columna = 5;
        idPaciente = Integer.valueOf(tblPacientes.getModel().getValueAt(fila, columna).toString());
        //crudHistoria.setFocusable(true);
    }//GEN-LAST:event_tblPacientesMouseClicked

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        this.crudHistoria.llenarDatosHistoriaPorPaciente(idPaciente);
        this.dispose();
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.crudHistoria.configurarControles(false);
    }//GEN-LAST:event_formWindowClosing

    private void txtCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyPressed

        codigoHistoria =txtCodigo.getText();
        List<Paciente> pacientes = pacienteControlador.buscarPacientePorNombre(codigoHistoria);

        modelo = (DefaultTableModel) this.tblPacientes.getModel();
        modelo.setRowCount(0);
        Object[] filadata = new Object[6];
        for (Paciente paciente : pacientes) {
            filadata[0] = paciente.getDni();
            filadata[1] = paciente.getNombre();
            filadata[2] = paciente.getEdad();
            filadata[3] = paciente.getSexo();
            filadata[4] = paciente.getEstaoCivil();
            filadata[5] = paciente.getId();
            
            modelo.addRow(filadata);
        }
    }//GEN-LAST:event_txtCodigoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaPacientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPacientes;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JLabel txtNombre;
    // End of variables declaration//GEN-END:variables
}
